# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/schemas/market_data.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/schemas/market_data.proto\x12\ncryptochart\"\xad\x01\n\x0bPriceUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\t\x12\x0c\n\x04side\x18\x05 \x01(\t\x12 \n\x18\x65xchange_timestamp_utc\x18\x06 \x01(\t\x12%\n\x1d\x63lient_received_timestamp_utc\x18\x07 \x01(\t\"\xab\x01\n\x13\x41ggregatedDataPoint\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x15\n\rtimestamp_utc\x18\x03 \x01(\t\x12\x0c\n\x04vwap\x18\x04 \x01(\t\x12\x1b\n\x13\x63umulative_volume\x18\x05 \x01(\t\x12\x12\n\nlast_price\x18\x06 \x01(\t\x12\x0f\n\x07high_price\x18\x07 \x01(\t\x12\x10\n\x08low_price\x18\x08 \x01(\t\"\x8d\x01\n\x06\x43\x61ndle\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x15\n\ropen_time_utc\x18\x03 \x01(\t\x12\x0c\n\x04open\x18\x04 \x01(\t\x12\x0c\n\x04high\x18\x05 \x01(\t\x12\x0b\n\x03low\x18\x06 \x01(\t\x12\r\n\x05\x63lose\x18\x07 \x01(\t\x12\x0e\n\x06volume\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.schemas.market_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['PRICEUPDATE']._serialized_start=46
  _globals['PRICEUPDATE']._serialized_end=219
  _globals['AGGREGATEDDATAPOINT']._serialized_start=222
  _globals['AGGREGATEDDATAPOINT']._serialized_end=393
  _globals['CANDLE']._serialized_start=396
  _globals['CANDLE']._serialized_end=537
# @@protoc_insertion_point(module_scope)