name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  quality_gate:
    name: "1. Lint, Type Check, and Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Lint with Ruff
        run: poetry run ruff check .

      - name: Type check with MyPy
        run: poetry run mypy .

      - name: Scan for dependency vulnerabilities with pip-audit
        run: poetry run pip-audit

  test_suite:
    name: "2. Unit & Integration Tests"
    needs: quality_gate
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install --with dev --extras "desktop mobile"

      - name: Generate Protobuf code
        run: |
          poetry run python -m grpc_tools.protoc -I=src/schemas --python_out=src/schemas src/schemas/market_data.proto
          touch src/schemas/__init__.py

      - name: Run Pytest
        run: poetry run pytest --cov=src/app_core --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  build_desktop:
    name: "3. Build & Sign Desktop Binaries"
    needs: test_suite
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      # ** FIX **: Check for secret existence here and set an env var.
      WINDOWS_PFX_B64_PRESENT: ${{ secrets.WINDOWS_PFX_B64 != '' }}
      APPLE_ID_PRESENT: ${{ secrets.APPLE_ID != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry and build dependencies
        run: |
          python -m pip install poetry pyinstaller
          poetry install --extras "desktop"

      - name: Generate Protobuf code
        run: |
          poetry run python -m grpc_tools.protoc -I=src/schemas --python_out=src/schemas src/schemas/market_data.proto
          touch src/schemas/__init__.py

      - name: Package with PyInstaller
        run: poetry run pyinstaller build-specs/desktop.spec --noconfirm

      - name: Sign Windows Executable
        # ** FIX **: Check the env var instead of the secret directly.
        if: runner.os == 'Windows' && env.WINDOWS_PFX_B64_PRESENT == 'true'
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: ${{ secrets.WINDOWS_PFX_B64 }}
          password: ${{ secrets.WINDOWS_PFX_PASSWORD }}
          folder: dist/windows
          recursive: true
          timestamp_url: http://timestamp.sectigo.com

      - name: Sign and Notarize macOS App
        # ** FIX **: Check the env var.
        if: runner.os == 'macOS' && env.APPLE_ID_PRESENT == 'true'
        run: echo "Signing and notarizing on macOS..." # Placeholder for complex signing logic

      - name: Prepare Artifact
        # ** FIX **: Consolidated artifact packaging for all platforms.
        id: prepare_artifact
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a -tzip App-windows-x64.zip ./dist/windows/*
            echo "artifact_path=App-windows-x64.zip" >> $GITHUB_OUTPUT
            echo "artifact_name=App-Windows-x64" >> $GITHUB_OUTPUT
          elif [ "${{ runner.os }}" == "macOS" ]; then
            hdiutil create -volname CryptoChart -srcfolder dist/macos/CryptoChart.app -ov -format UDZO App-macos.dmg
            echo "artifact_path=App-macos.dmg" >> $GITHUB_OUTPUT
            echo "artifact_name=App-macOS" >> $GITHUB_OUTPUT
          fi

      - name: Upload Artifact
        # ** FIX **: Single, robust upload step.
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepare_artifact.outputs.artifact_name }}
          path: ${{ steps.prepare_artifact.outputs.artifact_path }}
          path-if-no-files-found: error

  build_mobile_debug:
    name: "4. Build Android Debug APK"
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Buildozer environment
        uses: kivy/buildozer-action@v1
        with:
          buildozer_version: master
      
      - name: Build with Buildozer (Debug)
        # 'debug' command auto-generates and uses a debug key. No secrets needed.
        run: buildozer --log_level 2 android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Android-debug
          path: bin/*.apk
          path-if-no-files-found: error
          
  create_release:
    name: "5. Publish GitHub Release"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [build_desktop, build_mobile_debug]
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          # ** FIX **: Updated paths to match new artifact names.
          files: |
            artifacts/App-Windows-x64/App-windows-x64.zip
            artifacts/App-macOS/App-macos.dmg
            artifacts/App-Android-debug/*.apk